import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://preprod.origamirisk.com/Origami/Account/Login?account=Mission_Pre_Prod');
  await page.getByRole('textbox', { name: 'User Name' }).click();
  await page.getByRole('textbox', { name: 'User Name' }).fill('rennel.nayan@rcggs.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('@04TestTest2025');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForTimeout(5000);
  await page.getByText('In preparation for the').click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('indigo');
  await page.getByRole('button', { name: 'Initiate Search' }).click();
  await page.getByLabel('Clients Data Grid').getByRole('link', { name: 'Indigo' }).click();
  await page.getByRole('link', { name: 'New Submission' }).click();
  await page.getByRole('link', { name: 'Indigo Primary MPL' }).click();
  //await page.waitForTimeout(5000);
  await page.locator('label').filter({ hasText: 'Existing' }).getByLabel('New or Existing Insured').check();
  await page.getByRole('combobox', { name: 'Insured' }).click();
  await page.getByRole('combobox', { name: 'Insured' }).click();
  await page.getByRole('combobox', { name: 'Insured' }).fill(' Automation Regression Insured_08/05/2025 00:21:12');
  await page.getByRole('textbox', { name: 'DUNS Number' }).click();
  await page.getByRole('combobox', { name: 'Insured' }).click();
  await page.getByRole('combobox', { name: 'Insured' }).click();
  await page.getByRole('combobox', { name: 'Insured' }).fill('Automation Regression Cancel Policy_08/05/2025 00:14:49');
  await page.getByText('Automation Regression Cancel').click();
  await page.getByLabel('Quoting Process Status').selectOption('69793');
  await page.getByRole('listitem').filter({ hasText: 'Agency:' }).getByRole('button').click();
  await page.locator('iframe[name="dialogFrame"]').contentFrame().getByRole('row', { name: 'AmWINS - Atlanta 8345606 3630' }).getByRole('link').click();
  await page.getByRole('listitem').filter({ hasText: 'Agent:' }).getByRole('button').click();
  await page.locator('iframe[name="dialogFrame"]').contentFrame().getByRole('link', { name: '0221008' }).click();
  await page.getByLabel('Applicant is').selectOption('69519');
  await page.locator('#useraction_next').click();
  await page.goto('https://preprod.origamirisk.com/Origami/Proposals/Interview');
  await page.getByLabel('Duplicate Proposal Override').selectOption('True');
  await page.locator('#useraction_next').click();
  await page.getByRole('combobox', { name: 'Area of Practice' }).click();
  await page.getByRole('combobox', { name: 'Area of Practice' }).fill('');
  await page.getByRole('combobox', { name: 'Area of Practice' }).press('CapsLock');
  await page.getByRole('combobox', { name: 'Area of Practice' }).fill('AP');
  await page.getByRole('combobox', { name: 'Area of Practice' }).press('CapsLock');
  await page.getByRole('combobox', { name: 'Area of Practice' }).fill('AP00');
  await page.getByText('Accounting Service - Audit/').click();
  await page.getByRole('textbox', { name: 'Gross revenues for current' }).click();
  await page.getByRole('textbox', { name: 'Gross revenues for current' }).fill('2021');
  await page.getByRole('textbox', { name: 'Definition of Professional' }).click();
  await page.getByRole('textbox', { name: 'Definition of Professional' }).fill('test');
  await page.locator('#useraction_next').click();
  await page.goto('https://preprod.origamirisk.com/Origami/Proposals/Interview');
  await page.locator('label').filter({ hasText: /^No$/ }).getByLabel('Loss Information status').check();
  await page.locator('#useraction_next').click();
  await page.goto('https://preprod.origamirisk.com/Origami/Proposals/Interview');
  await page.getByRole('link', { name: 'Indigo Endorsements' }).click();
  await page.locator('iframe[name="dialogFrame"]').contentFrame().getByRole('checkbox', { name: 'MS MPL 350005 03 22 -' }).check();
  await page.locator('iframe[name="dialogFrame"]').contentFrame().getByRole('button', { name: 'Save Changes' }).click();
  await page.locator('#useraction_save').click();
});